
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin/"
      - "/opt/homebrew/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/dmitryginzburg/.volta/bin/"
      - "/Users/dmitryginzburg/.vscode/extensions/ms-python.debugpy-2025.14.1-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/usr/local/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Users/dmitryginzburg/.volta/bin"
        - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin"
        - "/opt/homebrew/bin"
        - "/Users/dmitryginzburg/.vscode/extensions/ms-python.debugpy-2025.14.1-darwin-arm64/bundled/scripts/noConfigScripts"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 21.5.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin/"
      - "/opt/homebrew/bin/"
      - "/usr/local/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/Users/dmitryginzburg/.volta/bin/"
      - "/Users/dmitryginzburg/.vscode/extensions/ms-python.debugpy-2025.14.1-darwin-arm64/bundled/scripts/noConfigScripts/"
    searched_directories:
      - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/bin"
        - "/usr/local/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/Users/dmitryginzburg/.volta/bin"
        - "/Users/dmitryginzburg/.nvm/versions/node/v22.18.0/bin"
        - "/opt/homebrew/bin"
        - "/Users/dmitryginzburg/.vscode/extensions/ms-python.debugpy-2025.14.1-darwin-arm64/bundled/scripts/noConfigScripts"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
